Deploy etcd before DatenLord.
1. DatenLord rely on etcd. Deploy etcd before DatenLord
to avoid DatenLord crash.
2. Add deploy script.
3. transfer cron.yml to two scripts

diff --git a/.github/workflows/cron.yml b/.github/workflows/cron.yml
--- a/.github/workflows/cron.yml
+++ b/.github/workflows/cron.yml
@@ -8,12 +8,14 @@ env:
   RUST_VERSION: 1.47.0
   CONFIG_MINIKUBE: scripts/datenlord_minikube.yaml
   CONFIG_KIND: scripts/datenlord.yaml
-  CONFIG_DOCKERHUB: datenlord-deploy.yaml
+  CONFIG_DOCKERHUB: scripts/datenlord-deploy.yaml
   CONTROLLER_APP_LABEL: csi-controller-datenlord
   CONTROLLER_CONTAINER_NAME: datenlord-controller-plugin
   DATENLORD_CSI_IMAGE: datenlord/csiplugin:e2e_test
+  DATENLORD_ETCD: scripts/datenlord-etcd.yaml
   DATENLORD_IMAGE: datenlord/datenlord:e2e_test
   DATENLORD_NAMESPACE: csi-datenlord
+  ETCD_APP_LABEL: csi-etcd
   E2E_TEST_CONFIG: scripts/datenlord-e2e-test.yaml
   FUSE_CONTAINER_NAME: datenlord-fuse
   FUSE_MOUNT_PATH: /var/opt/datenlord-data
@@ -152,106 +154,121 @@ jobs:
     steps:
       - name: Check out code
         uses: actions/checkout@v2
-      - name: Install Kind
+      - name: Setup Test Environment
         run: |
-          curl -Lo ./kind https://kind.sigs.k8s.io/dl/$KIND_VERSION/kind-linux-amd64
-          chmod +x ./kind
-          sudo mv ./kind /usr/local/bin
-      - name: Create Kind Cluster
-        run: |
-          cat >> ./kind-config.yaml <<END
-          # Kind cluster with 1 control plane node and 3 workers
-          kind: Cluster
-          apiVersion: kind.x-k8s.io/v1alpha4
-          nodes:
-          # the control plane node config
-          - role: control-plane
-          # the three workers
-          - role: worker
-            image: $KIND_NODE_VERSION
-          - role: worker
-            image: $KIND_NODE_VERSION
-          - role: worker
-            image: $KIND_NODE_VERSION
-          END
-          kind create cluster --config ./kind-config.yaml
-      - name: Setup SSH
-        run: |
-          cat >>/tmp/setup.sh <<'END'
-          NODES_IP="$(kubectl get nodes -A -o wide | awk 'FNR > 2 {print $6}')"
-          NODES="$(kubectl get nodes -A -o wide | awk 'FNR > 2 {print $1}')"
-          for node in ${NODES}; do
-            USER="$(whoami)"
-            docker exec ${node} apt-get update
-            docker exec ${node} apt-get install -y ssh sudo
-            docker exec ${node} systemctl start sshd
-            docker exec ${node} useradd -m ${USER}
-            docker exec ${node} usermod -aG sudo ${USER}
-            echo "${USER} ALL=(ALL) NOPASSWD:ALL" > /tmp/${USER}
-            docker cp /tmp/${USER} ${node}:/etc/sudoers.d/${USER}
-            docker exec ${node} chown root:root /etc/sudoers.d/${USER}
+          ./scripts/cron-setup.sh
+          #- name: Install Kind
+          #  run: |
+          #    curl -Lo ./kind https://kind.sigs.k8s.io/dl/$KIND_VERSION/kind-linux-amd64
+          #    chmod +x ./kind
+          #    sudo mv ./kind /usr/local/bin
+          #- name: Create Kind Cluster
+          #  run: |
+          #    cat >> ./kind-config.yaml <<END
+          #    # Kind cluster with 1 control plane node and 3 workers
+          #    kind: Cluster
+          #    apiVersion: kind.x-k8s.io/v1alpha4
+          #    nodes:
+          #    # the control plane node config
+          #    - role: control-plane
+          #    # the three workers
+          #    - role: worker
+          #      image: $KIND_NODE_VERSION
+          #    - role: worker
+          #      image: $KIND_NODE_VERSION
+          #    - role: worker
+          #      image: $KIND_NODE_VERSION
+          #    END
+          #    kind create cluster --config ./kind-config.yaml
+          #- name: Setup SSH
+          #  run: |
+          #    cat >>/tmp/setup.sh <<'END'
+          #    NODES_IP="$(kubectl get nodes -A -o wide | awk 'FNR > 2 {print $6}')"
+          #    NODES="$(kubectl get nodes -A -o wide | awk 'FNR > 2 {print $1}')"
+          #    for node in ${NODES}; do
+          #      USER="$(whoami)"
+          #      docker exec ${node} apt-get update
+          #      docker exec ${node} apt-get install -y ssh sudo
+          #      docker exec ${node} systemctl start sshd
+          #      docker exec ${node} useradd -m ${USER}
+          #      docker exec ${node} usermod -aG sudo ${USER}
+          #      echo "${USER} ALL=(ALL) NOPASSWD:ALL" > /tmp/${USER}
+          #      docker cp /tmp/${USER} ${node}:/etc/sudoers.d/${USER}
+          #      docker exec ${node} chown root:root /etc/sudoers.d/${USER}
 
-            docker exec ${node} mkdir /home/${USER}/.ssh
-            docker exec ${node} ls -al /home/${USER}/
-            docker cp ${HOME}/.ssh/id_rsa.pub ${node}:/home/${USER}/.ssh/authorized_keys
-            docker exec ${node} chown ${USER}:${USER} /home/${USER}/ -R
-          done
-          for ip in ${NODES_IP}; do
-              ssh-keyscan -H $ip >> ${HOME}/.ssh/known_hosts
-          done
-          END
+          #      docker exec ${node} mkdir /home/${USER}/.ssh
+          #      docker exec ${node} ls -al /home/${USER}/
+          #      docker cp ${HOME}/.ssh/id_rsa.pub ${node}:/home/${USER}/.ssh/authorized_keys
+          #      docker exec ${node} chown ${USER}:${USER} /home/${USER}/ -R
+          #    done
+          #    for ip in ${NODES_IP}; do
+          #        ssh-keyscan -H $ip >> ${HOME}/.ssh/known_hosts
+          #    done
+          #    END
 
-          rm -rf $HOME/.ssh/
-          ssh-keygen -N '' -f ~/.ssh/id_rsa
-          /bin/bash /tmp/setup.sh
-      - name: Docker build fuse and csi
-        run: |
-          docker build . --build-arg RUST_IMAGE_VERSION=$RUST_VERSION --file ./Dockerfile --target fuse --tag $DATENLORD_IMAGE
-          docker build . --build-arg RUST_IMAGE_VERSION=$RUST_VERSION --file ./Dockerfile --target csi --tag $DATENLORD_CSI_IMAGE
-          kind load docker-image $DATENLORD_IMAGE
-          kind load docker-image $DATENLORD_CSI_IMAGE
+          #    rm -rf $HOME/.ssh/
+          #    ssh-keygen -N '' -f ~/.ssh/id_rsa
+          #    /bin/bash /tmp/setup.sh
+          #- name: Docker build fuse and csi
+          #  run: |
+          #    docker build . --build-arg RUST_IMAGE_VERSION=$RUST_VERSION --file ./Dockerfile --target fuse --tag $DATENLORD_IMAGE
+          #    docker build . --build-arg RUST_IMAGE_VERSION=$RUST_VERSION --file ./Dockerfile --target csi --tag $DATENLORD_CSI_IMAGE
+          #    kind load docker-image $DATENLORD_IMAGE
+          #    kind load docker-image $DATENLORD_CSI_IMAGE
       - name: Deploy DatenLord to K8S
         run: |
-          kubectl cluster-info
-          kubectl get pods -A
-          kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
-          kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
-          kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
-          kubectl apply -f $CONFIG_KIND
-          kubectl wait --for=condition=Ready pod -l app=$CONTROLLER_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
-          kubectl wait --for=condition=Ready pod -l app=$NODE_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
-          FOUND_PATH=`cat /proc/self/mountinfo | grep fuse | grep $FUSE_MOUNT_PATH | awk '{print $5}'`
-          test -n $FOUND_PATH || (echo "FAILED TO FIND MOUNT PATH $FUSE_MOUNT_PATH" && /bin/false)
-          kubectl delete -f $CONFIG_KIND
-          NO_PATH=`cat /proc/self/mountinfo | grep fuse | grep $FUSE_MOUNT_PATH | awk '{print $5}'`
-          test -z $NO_PATH || (echo "FAILED TO UN-MOUNT PATH $FUSE_MOUNT_PATH" && /bin/false)
-          kubectl apply -f $CONFIG_KIND
-          kubectl get csidriver
-          kubectl get csinode
-          kubectl get storageclass
-          kubectl get volumesnapshotclass
-          kubectl wait --for=condition=Ready pod -l app=$CONTROLLER_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
-          kubectl wait --for=condition=Ready pod -l app=$NODE_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
-          wget https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
-          wget https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
-          sed -e 's/namespace\:\ default/namespace\:\ kube\-system/g' rbac-snapshot-controller.yaml > datenlord-rbac-snapshot-controller.yaml
-          sed -e 's/namespace\:\ default/namespace\:\ kube\-system/g' setup-snapshot-controller.yaml > datenlord-setup-snapshot-controller.yaml
-          kubectl apply -f datenlord-rbac-snapshot-controller.yaml
-          kubectl apply -f datenlord-setup-snapshot-controller.yaml
-          kubectl wait --for=condition=Ready pod -l app=snapshot-controller -n kube-system --timeout=60s
-          kubectl get pods -A -o wide
-          # sudo netstat -lntp && ls -lsh
+          ./scripts/cron-e2e.sh deploy
+            #  kubectl cluster-info
+            #  kubectl get pods -A
+            #  #kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshots.yaml
+            #  #kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotcontents.yaml
+            #  #kubectl apply -f https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/client/config/crd/snapshot.storage.k8s.io_volumesnapshotclasses.yaml
+            #  #kubectl apply -f $DATENLORD_ETCD
+            #  #kubectl wait --for=condition=Ready pod -l app=$ETCD_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
+            #  #kubectl apply -f $CONFIG_KIND
+            #  #kubectl wait --for=condition=Ready pod -l app=$CONTROLLER_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
+            #  #kubectl wait --for=condition=Ready pod -l app=$NODE_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
+            #  ./scripts/datenlord-deploy.sh deploy
+            #  FOUND_PATH=`cat /proc/self/mountinfo | grep fuse | grep $FUSE_MOUNT_PATH | awk '{print $5}'`
+            #  test -n $FOUND_PATH || (echo "FAILED TO FIND MOUNT PATH $FUSE_MOUNT_PATH" && /bin/false)
+            #  #kubectl delete -f $CONFIG_KIND
+            #  #kubectl delete -f $DATENLORD_ETCD
+            #  ./scripts/datenlord-deploy.sh deploy undeploy
+            #  NO_PATH=`cat /proc/self/mountinfo | grep fuse | grep $FUSE_MOUNT_PATH | awk '{print $5}'`
+            #  test -z $NO_PATH || (echo "FAILED TO UN-MOUNT PATH $FUSE_MOUNT_PATH" && /bin/false)
+            #  #kubectl apply -f $DATENLORD_ETCD
+            #  #kubectl wait --for=condition=Ready pod -l app=$ETCD_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
+            #  #kubectl apply -f $CONFIG_KIND
+            #  ./scripts/datenlord-deploy.sh deploy
+            #  kubectl get csidriver
+            #  kubectl get csinode
+            #  kubectl get storageclass
+            #  kubectl get volumesnapshotclass
+            #  #kubectl wait --for=condition=Ready pod -l app=$CONTROLLER_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
+            #  #kubectl wait --for=condition=Ready pod -l app=$NODE_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
+            #  wget https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/snapshot-controller/rbac-snapshot-controller.yaml
+            #  wget https://raw.githubusercontent.com/kubernetes-csi/external-snapshotter/master/deploy/kubernetes/snapshot-controller/setup-snapshot-controller.yaml
+            #  sed -e 's/namespace\:\ default/namespace\:\ kube\-system/g' rbac-snapshot-controller.yaml > datenlord-rbac-snapshot-controller.yaml
+            #  sed -e 's/namespace\:\ default/namespace\:\ kube\-system/g' setup-snapshot-controller.yaml > datenlord-setup-snapshot-controller.yaml
+            #  kubectl apply -f datenlord-rbac-snapshot-controller.yaml
+            #  kubectl apply -f datenlord-setup-snapshot-controller.yaml
+            #  kubectl wait --for=condition=Ready pod -l app=snapshot-controller -n kube-system --timeout=60s
+            #  kubectl get pods -A -o wide
+            #  # sudo netstat -lntp && ls -lsh
       - name: CSI E2E Test
         run: |
-          wget --quiet https://dl.k8s.io/$K8S_VERSION/kubernetes-test-linux-amd64.tar.gz
-          tar zxvf kubernetes-test-linux-amd64.tar.gz
-          kubectl config view --raw > $K8S_CONFIG
-          #kubernetes/test/bin/e2e.test -v=5 -ginkgo.failFast -ginkgo.failOnPending -ginkgo.debug -ginkgo.v -ginkgo.focus='External.Storage' -kubectl-path=`which kubectl` -kubeconfig=$K8S_CONFIG -storage.testdriver=`realpath $E2E_TEST_CONFIG`
-          kubernetes/test/bin/ginkgo -p -v -failFast -failOnPending -debug -focus='External.Storage' -skip='.*Dynamic PV.*filesystem.*should access to two volumes with the same volume mode and retain data across pod recreation on .* node' kubernetes/test/bin/e2e.test -- -v=5 -kubectl-path=`which kubectl` -kubeconfig=`realpath $K8S_CONFIG` -storage.testdriver=`realpath $E2E_TEST_CONFIG` -test.parallel=3
+          ./scripts/cron-e2e.sh run
+            #wget --quiet https://dl.k8s.io/$K8S_VERSION/kubernetes-test-linux-amd64.tar.gz
+            #tar zxvf kubernetes-test-linux-amd64.tar.gz
+            #kubectl config view --raw > $K8S_CONFIG
+            ##kubernetes/test/bin/e2e.test -v=5 -ginkgo.failFast -ginkgo.failOnPending -ginkgo.debug -ginkgo.v -ginkgo.focus='External.Storage' -kubectl-path=`which kubectl` -kubeconfig=$K8S_CONFIG -storage.testdriver=`realpath $E2E_TEST_CONFIG`
+            #kubernetes/test/bin/ginkgo -p -v -failFast -failOnPending -debug -focus='External.Storage' -skip='.*Dynamic PV.*filesystem.*should access to two volumes with the same volume mode and retain data across pod recreation on .* node' kubernetes/test/bin/e2e.test -- -v=5 -kubectl-path=`which kubectl` -kubeconfig=`realpath $K8S_CONFIG` -storage.testdriver=`realpath $E2E_TEST_CONFIG` -test.parallel=3
       - name: Quick Start Test
         run: |
-          kubectl delete -f $CONFIG_KIND
+          ./scripts/datenlord-deploy.sh undeploy
           sed -e 's/e2e_test/latest/g' $CONFIG_KIND > $CONFIG_DOCKERHUB
+          kubectl apply -f $DATENLORD_ETCD
+          kubectl wait --for=condition=Ready pod -l app=$ETCD_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
           kubectl apply -f $CONFIG_DOCKERHUB
           kubectl wait --for=condition=Ready pod -l app=$CONTROLLER_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
           kubectl wait --for=condition=Ready pod -l app=$NODE_APP_LABEL -n $DATENLORD_NAMESPACE --timeout=60s
